name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # ---- Node.js Setup for Frontend ----
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # ---- Frontend: Install Dependencies and Build ----
      - name: Install and Build Frontend
        run: |
          cd frontend-react
          npm install
          npm run build -- --mode production

      # ---- Copy Frontend Files ----
      - name: Deploy Frontend
        run: |
          sudo rm -rf /var/www/estate-corp/frontend-react/*  # Clear existing frontend files
          sudo cp -r ./frontend-react/build/* /var/www/estate-corp/frontend-react/  # Assuming 'build' directory
          sudo chown -R root:root /var/www/estate-corp/frontend-react/
        working-directory: ./frontend-react

      # ---- Backend: Build Spring Boot ----
      - name: Build Backend (Spring Boot)
        run: |
          cd Backend
          mvn clean install -DskipTests

      # ---- Copy Backend JAR ----
      - name: Deploy Backend
        run: |
          sudo rm -rf /opt/my-app/*
          sudo cp ./Backend/target/*.jar /opt/my-app/
          sudo chown -R root:root /opt/my-app

      # ---- Restart Spring Boot ----
      - name: Restart Spring Boot App
        run: sudo systemctl restart springboot-app

      # ---- Restart Nginx ----
      - name: Restart Nginx
        run: sudo systemctl restart nginx
