name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # ---- Run the deploy.sh script ----
      - name: Run deployment script
        run: |
          chmod +x deploy.sh  # Ensure the script has execute permissions
          sudo ./deploy.sh    # Run the deployment script with sudo if required
