name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy Backend
        run: |
          sudo systemctl stop my-spring-boot-app
          sudo rm -rf /opt/my-app/*
          sudo cp -r backend/build/* /opt/my-app/
          sudo chown -R root:root /opt/my-app
          sudo systemctl start my-spring-boot-app
        working-directory: Backend

      - name: Deploy Frontend
        run: |
          sudo rm -rf /var/www/estate-corp/frontend-react/dist/*
          sudo cp -r ./frontend/build/* /var/www/estate-corp/frontend-react/dist/
          sudo chown -R root:root /var/www/estate-corp/frontend-react/dist
        working-directory: ./frontend

      - name: Reload Nginx
        run: sudo systemctl reload nginx
