name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      # ---- Backend Build ----
      - name: Build Backend (Spring Boot)
        run: |
          ./mvnw clean package
        working-directory: Backend

      - name: Deploy Backend
        run: |
          sudo systemctl stop my-spring-boot-app
          sudo rm -rf /opt/my-app/*
          sudo cp Backend/target/*.jar /opt/my-app/
          sudo chown -R root:root /opt/my-app
          mvn clean install -DskipTests
          sudo systemctl restart springboot-app
        working-directory: Backend

      # ---- Frontend Build ----
      - name: Install Dependencies (Frontend)
        run: |
          npm install
        working-directory: ./frontend-react

      - name: Build Frontend (React)
        run: |
          npm run build -- --mode production
        working-directory: ./frontend-react

      - name: Deploy Frontend
        run: |
          sudo rm -rf /var/www/estate-corp/frontend-react/dist/*
          sudo cp -r ./frontend-react/build/* /var/www/estate-corp/frontend-react/dist/
          sudo chown -R root:root /var/www/estate-corp/frontend-react/dist
        working-directory: ./frontend-react

      # ---- Reload Nginx ----
      - name: Reload Nginx
        run: sudo systemctl reload nginx
